spring.application.name=kymnevoistlus2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5433/kymnevoistlus2
spring.datasource.username=postgres
spring.datasource.password=root
